-- Taproot Stage 1 — Digests table
-- One row per workspace per week. Generated by the Sunday synthesis worker; written
-- via service role only. Dashboard reads via RLS-scoped SELECT.

create table digests (
  id               uuid primary key default gen_random_uuid(),
  workspace_id     uuid not null references workspaces(id) on delete cascade,
  generated_at     timestamptz not null default now(),
  week_starts_at   timestamptz not null,  -- monday 00:00 user-tz of the week summarized
  week_ends_at     timestamptz not null,  -- sunday 06:00 user-tz when this digest was sent
  persona_context  jsonb not null default '{}',
  bullets          jsonb not null,        -- array of { text, source_keys, evidence: [...] }
  email_sent_at    timestamptz,
  unique (workspace_id, week_starts_at)
);

create index digests_workspace_generated_idx
  on digests (workspace_id, generated_at desc);

alter table digests enable row level security;

-- Workspace members can read their own digests; all writes are service-role-only.
create policy "digests_select" on digests
  for select using (workspace_id in (select user_workspaces()));
